import 'models.dart';

/// Fake data used to demo the application.
final fakeData = [
  Todo(
    memberCapacity : 3,
    host : UserData(uid:'test_uid',
        email : 'a@a.com',
        nickName : 'ttt',
        location : '서울시 서초구',
        selfIntro : '하이요',
        ntrp : 4.0,
        gender : '남'),
    starttime : DateTime.parse("2021-07-20 20:00:00Z"),
    endtime : DateTime.parse("2021-07-20 22:00:00Z"),
    location : '시민의숲 테니스장',
    id : 'test_id',
    description : 'hihi',
  ),Todo(
    memberCapacity : 4,
    host : UserData(uid:'test_uid',
        email : 'a@a.com',
        nickName : 'ttt',
        location : '서울시 서초구',
        selfIntro : '하이요',
        ntrp : 4.0,
        gender : '남'),
    starttime : DateTime.parse("2021-07-20 20:00:00Z"),
    endtime : DateTime.parse("2021-07-20 22:00:00Z"),
    location : '시민의숲 테니스장',
    id : 'test_id2',
    description : 'hihi',
  ),Todo(
    memberCapacity : 2,
    host : UserData(uid:'test_uid',
        email : 'a@a.com',
        nickName : 'ttt',
        location : '서울시 서초구',
        selfIntro : '하이요',
        ntrp : 4.0,
        gender : '남'),
    starttime : DateTime.parse("2021-07-20 20:00:00Z"),
    endtime : DateTime.parse("2021-07-20 22:00:00Z"),
    location : '시민의숲 테니스장',
    id : 'test_id3',
    description : 'hihi',
  ),Todo(
    memberCapacity : 1,
    host : UserData(uid:'test_uid',
        email : 'a@a.com',
        nickName : 'ttt',
        location : '서울시 서초구',
        selfIntro : '하이요',
        ntrp : 4.0,
        gender : '남'),
    starttime : DateTime.parse("2021-07-20 20:00:00Z"),
    endtime : DateTime.parse("2021-07-20 22:00:00Z"),
    location : '시민의숲 테니스장',
    id : 'test_id4',
    description : 'hi',
  ),
];
